### ISSUE TITLE
make fails, "no rule to make target"

### ISSUE THREAD

**Issue by fabe** [starbloom/CHIP-usbboot#1]
Hey, first of thanks for doing this. I'm trying to build a kernel with NAT support, unfortunately when I run `make` it gives me this error:

```
vagrant@vagrant-ubuntu-trusty-32:~/CHIP-usbboot$ make
/bin/sh: 1: cd: can't cd to ../CHIP-buildroot/output/target/lib
/bin/sh: 1: cd: can't cd to ../CHIP-buildroot/output/target/lib
/bin/sh: 1: cd: can't cd to ../CHIP-buildroot/output/target/sbin
/bin/sh: 1: cd: can't cd to ../CHIP-buildroot/output/target/sbin
/bin/sh: 1: cd: can't cd to ../CHIP-buildroot/output/target/usr/lib
/bin/sh: 1: cd: can't cd to ../CHIP-buildroot/output/target/usr/lib
============ Assemble Image Begins ==============
mkdir -p output/image
mkdir -p output/target
mkdir -p output/target/etc
mkdir -p output/target/etc/init.d
mkdir -p output/target/dev
mkdir -p output/target/proc
mkdir -p output/target/sys
mkdir -p output/target/mnt
mkdir -p output/target/bin
make: *** No rule to make target `../CHIP-buildroot/output/images/u-boot-dtb.bin', needed by `output/image/u-boot-dtb.bin'.  Stop.
```

I've tried it with `sudo` and with different output directories. The `CHIP-buildroot/` directory should be set correctly. Am I doing something wrong here?

(btw, I've read that you've built a kernel with NAT support already before, any way to get my hands on that?)

**Comment by starbloom** [comment]
The quick easy way to get CHIP-buildroot is to
1. Get Ubuntu or Ubuntu VM.
2. Run the following commands

> git clone https://github.com/NextThingCo/CHIP-SDK
> cd CHIP-SDK/
> ./setup_ubuntu1404.sh
1. Wait for the download and compilation to finish.
2. Now go back to CHIP-usbboot root directory.  Modify the Makefile and point the `CHIP_BUILDROOT` to the CHIP-buildroot directory.

**Comment by starbloom** [comment]
Also refer to this config file to build NAT support.  It is tested on my chip.

https://bbs.nextthing.co/t/boot-and-test-your-custom-kernel-and-code-without-installation-through-fel-interface/9652/2

**Comment by fabe** [comment]
Thank you! Tried that but ended up using the [Renzo Kernel](http://www.raspibo.org/wiki/index.php/Compile_the_Linux_kernel_for_Chip:_my_personal_HOWTO) :)
